# Generated by Django 3.1.7 on 2021-03-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=35)),
                ('authors', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.CharField(blank=True, default='', max_length=35)),
                ('publication_date', models.DateField(blank=True, default='')),
                ('number_of_pages', models.IntegerField(blank=True, default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
